In [1]:
import numpy as np

1.  Use a biblioteca NumPy para criar um vetor de 24 valores aleatórios inteiros entre 10 e 20

In [2]:
arr = np.random.randint(10, 21, size=24)
arr

array([17, 16, 19, 19, 13, 18, 16, 11, 14, 14, 11, 10, 18, 12, 13, 16, 16,
       18, 15, 14, 20, 15, 14, 12])

a.  Crie uma cópia do vetor original e substitua os elemento do vetor com índice ímpar com o valor -5 (sem alterar o vetor original). 

In [3]:
# Cria uma cópia do array
arr_copy = arr.copy()

# Substitui os indices impares por -5
arr_copy[1::2] = -5

# Imprime array original
arr_copy

array([17, -5, 19, -5, 13, -5, 16, -5, 14, -5, 11, -5, 18, -5, 13, -5, 16,
       -5, 15, -5, 20, -5, 14, -5])

b.  Extraia do vetor original os valores entre 10 (inclusive) e 15 (inclusive)

In [4]:
extracted_values = arr[(arr >= 10) & (arr <= 15)]
extracted_values

array([13, 11, 14, 14, 11, 10, 12, 13, 15, 14, 15, 14, 12])

c.  Extraia do vetor original os valores superiores a 15.

In [5]:
extracted_values = arr[(arr > 15)]
extracted_values

array([17, 16, 19, 19, 18, 16, 18, 16, 16, 18, 20])

d.  Converta o vetor inicial  numa matriz M de 2 dimensões com 6 linhas e 4 colunas. 

In [6]:
M = arr.reshape(6, 4)
M

array([[17, 16, 19, 19],
       [13, 18, 16, 11],
       [14, 14, 11, 10],
       [18, 12, 13, 16],
       [16, 18, 15, 14],
       [20, 15, 14, 12]])

e.  Extraia da matriz M a segunda e terceira coluna. 

In [7]:
second_third_columns = M[:, 1:3]
second_third_columns

array([[16, 19],
       [18, 16],
       [14, 11],
       [12, 13],
       [18, 15],
       [15, 14]])

f.  Extraia da matriz M as duas últimas linhas. 

In [8]:
last_two_rows = M[-2:]
last_two_rows

array([[16, 18, 15, 14],
       [20, 15, 14, 12]])

g.  Empilhe as matrizes que resultaram das duas alíneas anteriores. Justifique o tipo 
de empilhamento usado (vertical ou horizontal)

In [9]:
np.hstack((M, second_third_columns))

array([[17, 16, 19, 19, 16, 19],
       [13, 18, 16, 11, 18, 16],
       [14, 14, 11, 10, 14, 11],
       [18, 12, 13, 16, 12, 13],
       [16, 18, 15, 14, 18, 15],
       [20, 15, 14, 12, 15, 14]])

In [10]:
np.vstack((M, last_two_rows))

array([[17, 16, 19, 19],
       [13, 18, 16, 11],
       [14, 14, 11, 10],
       [18, 12, 13, 16],
       [16, 18, 15, 14],
       [20, 15, 14, 12],
       [16, 18, 15, 14],
       [20, 15, 14, 12]])

h.  Use a matriz M e inverta a ordem dos elementos  da primeira coluna e da última 
coluna 

In [11]:
M[:,0] = M[::-1, 0]
M[:,-1] = M[::-1, -1]
M

array([[20, 16, 19, 12],
       [16, 18, 16, 14],
       [18, 14, 11, 16],
       [14, 12, 13, 10],
       [13, 18, 15, 11],
       [17, 15, 14, 19]])

i.  Use a matriz M e inverta a ordem dos elementos da primeira linha e última linha.

In [12]:
M[0,:] = M[0, ::-1]
M[-1,:] = M[-1, ::-1]
M

array([[12, 19, 16, 20],
       [16, 18, 16, 14],
       [18, 14, 11, 16],
       [14, 12, 13, 10],
       [13, 18, 15, 11],
       [19, 14, 15, 17]])

2.  O dataset iris contém informação sobre as dimensões (comprimento e largura) das 
sépalas e pétalas de três espécies de flores iris.  
O dataset pode ser lido da sua localização no repositório da UC Irvine para uma matriz 
numpy (iris) através das seguintes instruções:

In [13]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data' 
iris = np.genfromtxt(url, delimiter=',', dtype='float64')
iris[:5]

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan]])

a.  Verifique qual é a forma da matriz iris criada com as instruções anteriores. Cada 
linha corresponde a uma flor. Quantas flores estão representadas no dataset?

In [14]:
print(f'São represantadas {iris.shape[0]} flores no dataset')

São represantadas 150 flores no dataset


b.  Verifique  que  a  última  coluna  da  matriz  contém  elementos  que  não  são 
numéricos (nan) e descarte essa coluna da matriz. Verifique a alteração da forma 
da matriz.

In [15]:
iris = np.delete(iris, -1, axis=1)
iris.shape

(150, 4)

c.  Verifique agora se a matriz iris contém algum elemento que não seja um número 
(nan)

In [16]:
print(f'A matriz iris possui {np.isnan(iris).sum()} elementos NaN.')

A matriz iris possui 0 elementos NaN.


A primeira coluna de iris representa o comprimento das sépalas.    
A segunda coluna de iris representa a largura das sépalas    
A terceira coluna de iris representa o comprimento das pétalas    
A quarta coluna de iris representa a largura das pétalas   

d.  Determine a média, mediana e desvio padrão das quantidades representadas em 
cada coluna. 

In [17]:
mean_values = np.mean(iris, axis=0)
median_values = np.median(iris, axis=0)
std_values = np.std(iris, axis=0)

print("Médias: ", [i for i in mean_values])
print("Medianas: ", [i for i in median_values])
print("Desvios Padrão: ", [i for i in std_values])

Médias:  [5.843333333333335, 3.0540000000000007, 3.7586666666666693, 1.1986666666666672]
Medianas:  [5.8, 3.0, 4.35, 1.3]
Desvios Padrão:  [0.8253012917851409, 0.4321465800705435, 1.7585291834055201, 0.760612618588172]


e.  Ordene a matriz por ordem crescente de comprimento das pétalas. 

In [18]:
sorted_indices = np.argsort(iris[:, 2])
sorted_iris = iris[sorted_indices]
sorted_iris[:5]

array([[4.6, 3.6, 1. , 0.2],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5. , 3.5, 1.3, 0.3]])

f.  Crie uma segunda matriz que contém os elementos de iris em que o comprimento 
das pétalas é superior a 1.5 e o comprimento das sépalas é menor que 1.5. 
Quantos exemplares existem com essas duas condições?

In [19]:
second_matrix = iris[(iris[:, 2] > 1.5) & (iris[:, 0] < 1.5)]
num_exemplares = second_matrix.shape[0]
print(f'Existem {num_exemplares} exemplares que atendem aos critérios.')

Existem 0 exemplares que atendem aos critérios.
